timeDict = {
"Arizona": -7,
"Columbia": -5,
"France": 2,
"Netherlands": 2,
"India": 5.5,
"NewZealand": 13,
}

gmt = 12

for time in timeDict:
    

















# ArizonaTime = input("What time is it in Arizona rounded to next hour: ")
# ColumbiaTime = int(ArizonaTime) + 2
# FranceTime = int(ArizonaTime) + 9
# NetherlandsTime = int(ArizonaTime) + 9
# IndiaTime = int(ArizonaTime) + 12.5
# NewZealandTime = int(ArizonaTime) + 13






# print(f"{ArizonaTime} Arizona Time")
# print(f"{ColumbiaTime} Columbia Time")
# print(f"{FranceTime} France Time")
# print(f"{IndiaTime} India Time")
# print(f"{NetherlandsTime} Netherlands Time")
# print(F"{NewZealandTime} NewZealand Time")


